"""Initial Schema

Revision ID: 01ac7040ab76
Revises: 
Create Date: 2026-02-08 16:19:25.297062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ac7040ab76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('daily_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_sentiment', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('headline_count', sa.Integer(), nullable=True),
    sa.Column('top_headline', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['assets.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_daily_sentiment_symbol_date')
    )
    op.create_index('idx_daily_sentiment_symbol_date', 'daily_sentiment', ['symbol', 'date'], unique=False)
    op.create_table('headlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['assets.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_headlines_symbol_date', 'headlines', ['symbol', 'date'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('predicted_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('actual_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['assets.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['assets.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_price_symbol_date')
    )
    op.create_index('idx_prices_symbol_date', 'prices', ['symbol', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prices_symbol_date', table_name='prices')
    op.drop_table('prices')
    op.drop_table('predictions')
    op.drop_index('idx_headlines_symbol_date', table_name='headlines')
    op.drop_table('headlines')
    op.drop_index('idx_daily_sentiment_symbol_date', table_name='daily_sentiment')
    op.drop_table('daily_sentiment')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('assets')
    # ### end Alembic commands ###
