"""Initial migration

Revision ID: 65950c4cc380
Revises: 
Create Date: 2026-02-10 16:41:06.094429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65950c4cc380'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('daily_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_sentiment', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('headline_count', sa.Integer(), nullable=True),
    sa.Column('top_headline', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['assets.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_daily_sentiment_symbol_date')
    )
    with op.batch_alter_table('daily_sentiment', schema=None) as batch_op:
        batch_op.create_index('idx_daily_sentiment_symbol_date', ['symbol', 'date'], unique=False)

    op.create_table('headlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['assets.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('headlines', schema=None) as batch_op:
        batch_op.create_index('idx_headlines_symbol_date', ['symbol', 'date'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('predicted_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('actual_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['assets.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'prediction_date', name='uq_prediction_symbol_date')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index('idx_predictions_symbol_date', ['symbol', 'prediction_date'], unique=False)

    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['assets.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_price_symbol_date')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index('idx_prices_symbol_date', ['symbol', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index('idx_prices_symbol_date')

    op.drop_table('prices')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index('idx_predictions_symbol_date')

    op.drop_table('predictions')
    with op.batch_alter_table('headlines', schema=None) as batch_op:
        batch_op.drop_index('idx_headlines_symbol_date')

    op.drop_table('headlines')
    with op.batch_alter_table('daily_sentiment', schema=None) as batch_op:
        batch_op.drop_index('idx_daily_sentiment_symbol_date')

    op.drop_table('daily_sentiment')
    op.drop_table('assets')
    # ### end Alembic commands ###
